### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by hexylena** [GMOD/docker-apollo#1]
FYI, just documenting in case these aren't the same build issues you see...

```
:clean-grails[ant:exec] Execute failed: java.io.IOException: Cannot run program "grails": error=2, No such file or directory
```

and

```
bower ESUDO         Cannot be run with sudo
```

**Comment by nathandunn** [comment]
The second one should be fixed (as it does cause problems), but I'll double-check.   I'm going to refactor to fix the first one.  While its not technically wrong, it is not correct either.
