### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by fikipollo** [GMOD/docker-apollo#21]
Hi @nathandunn 

Just a question "out of the topic", Do you now where can I find some test data for Webapollo? All the documentation and tutorials uses the "pyu_data" but it is not available anymore at http://genomearchitect.org/webapollo/data/pyu_data.tgz

Thanks

Rafa

**Comment by nathandunn** [comment]
Thanks.  Can you provide me with a sample link from where its linking from?

We’re trying to retire that server anyway, so I need to update the link.

Thanks,    

Nathan

**Comment by nathandunn** [comment]
I also moved the data back there so you can find it in the interim (while I fix other links).  Thanks.

**Comment by fikipollo** [comment]
Many thanks! I found the link in some old tutorials such as the [GMOD WebApollo tutorial 2013](http://gmod.org/wiki/WebApollo_Tutorial_2013) and in old readthedocs entries (just google _pyu_data webapollo_), but in any case even in the latest version of the documentation you use the pyu_data at the _Data generation pipeline_ section but there is not information about where can we find the same data.
