### ISSUE TITLE
pg user / password is not passed to psql

### ISSUE THREAD

**Issue by epaule** [GMOD/docker-apollo#22]
in docker-apollo/launch.sh on master

you probably want:
a.) PGPASSWORD=$WEBAPOLLO_DB_PASSWORD passed along
b.) a -U $WEBAPOLLO_DB_PASSWORD passed into the options

**Comment by nathandunn** [comment]
Shoot, would it be possible for you to submit a PR?

If not, I can do it, but I’d rather pull straight off of your working copy.  

Thanks,

Nathan

**Comment by epaule** [comment]
Can do. Just need to create a clean branch for the PR.
But my hack doesn't fix the logic bit that you most likely wont be able to
create the pg user / database as the user itself.

**Comment by nathandunn** [comment]
@epaule   I can push to your PR to fix anything additional.  Thanks.

**Comment by nathandunn** [comment]
closed by #23
