### ISSUE TITLE
Apollo docker running... but now ?

### ISSUE THREAD

**Issue by agroppi** [GMOD/docker-apollo#28]
Hi,

After many unsuccesfull try to install Apollo, I shifted to the docker version : 
But, I realise that it's impossible to add data after that.
I have to generate the data (ref genome, and all gff file) inside a jbrowse-data 
directory and after that run apollo-docker
Am I right ?
But in this case, where can I find the scripts described here : https://genomearchitect.readthedocs.io/en/latest/Data_loading.html#data-generation-pipeline

Thanks

**Comment by nathandunn** [comment]
> After many unsuccesfull try to install Apollo

What were the errors / what was your system?

> I have to generate the data (ref genome, and all gff file) inside a jbrowse-data
directory and after that run apollo-docker
> Am I right ?

Yes.  You have to mount it with the `-v` options.

> But in this case, where can I find the scripts described here : https://genomearchitect.readthedocs.io/en/latest/Data_loading.html#data-generation-pipeline

Those scripts are within the JBrowse directory, either in jbrowse/bin or bin

Conversely, if you use indexed fasta and tabix gff3, you can just manually edit the trackList.json / tracks.conf

Examples of both are in here:

http://jbrowse.org/docs/tutorial.html

**Comment by agroppi** [comment]
> > 
> > After many unsuccesfull try to install Apollo
> 
> What were the errors / what was your system?

It seems that the problem is linked to mysql (MariaDB). 
When I omit to install MariaDB, the the local instance `./apollo run-local` is working

I'm working on CentOS7

> 
> > I have to generate the data (ref genome, and all gff file) inside a jbrowse-data
> > directory and after that run apollo-docker
> > Am I right ?
> 
> Yes. You have to mount it with the `-v` options.
> 
> > But in this case, where can I find the scripts described here : https://genomearchitect.readthedocs.io/en/latest/Data_loading.html#data-generation-pipeline
> 
> Those scripts are within the JBrowse directory, either in jbrowse/bin or bin

OK but, inside the docker ... I will grep them from the github and execute outside the container
> 
> Conversely, if you use indexed fasta and tabix gff3, you can just manually edit the trackList.json / tracks.conf
> 
> Examples of both are in here:
> 
> http://jbrowse.org/docs/tutorial.html

Thanks :)
