### ISSUE TITLE
How to edit annot.json in the docker ?

### ISSUE THREAD

**Issue by agroppi** [GMOD/docker-apollo#29]
I want to add custom tracks (like pfam domains, blast results, etc ...)
I have these data in gff format, but for example the type "domain" is not present in the annot.json
```
perl /home/apollo/jbrowse-master/bin/flatfile-to-json.pl \
> --gff /home/apollo/rawdata/pfam_domains.gff \
> --type domain \
> --trackLabel pfam_domains \
> --out /home/apollo/jbrowse-data
WARNING: No matching features found for domain
```
Is there a solution ?

Thanks

**Comment by nathandunn** [comment]
Is this related to: https://github.com/GMOD/Apollo/issues/1948? 

If so, close this in favor of that.    Thanks.

**Comment by agroppi** [comment]
> Is this related to: [GMOD/Apollo#1948](https://github.com/GMOD/Apollo/issues/1948)?
> 
> If so, close this in favor of that. Thanks.

Yes sorry for that. Samme question as https://github.com/GMOD/Apollo/issues/1948
