### ISSUE TITLE
Increasing max memory inside container?

### ISSUE THREAD

**Issue by marchoeppner** [GMOD/docker-apollo#31]
Hi,
I have been running the WA docker container successfully for some time. Now I wanted to implement a backup routine for the curation track of a vertebrate genome (> 20.000 models). I get a an out of memory error when doing this from outside the container using the groovy get_gff3.groovy script that is bundled with WA.

The machine has plenty RAM, but I think the tomcat server inside the docker container is configured with too little. 

Since I have little experience with Docker - can I somwhow increase the max memory available to Tomcat inside the container?

Cheers,
Marc

**Comment by nathandunn** [comment]
I haven’t done it, but if you are able to figure out a solution, please open a PR for it, as I think at least GB would be useful. 

https://stackoverflow.com/questions/29923531/how-to-set-java-heap-size-xms-xmx-inside-docker-container <https://stackoverflow.com/questions/29923531/how-to-set-java-heap-size-xms-xmx-inside-docker-container>

Nathan

**Comment by nathandunn** [comment]
@marchoeppner  Most likely you'll be updating the `launch.sh` script.   I'm sure there will be several ways to do it.  Unfortunately, I have to look at other stuff. 

Might be worth posting to the Apollo list, though, as someone there has already done this.

**Comment by hodgett** [comment]
Has anyone figured this one out yet? I have tried passing JAVA_OPTS and CATALINA_OPTS using -e but they don't take. The memory allocated is way too small to handle the datasets and I get the following err for the bam track;
![screenshot from 2019-03-02 07-12-22](https://user-images.githubusercontent.com/24687753/53666723-a4530a80-3cba-11e9-8386-724fa19d4f23.png)

**Comment by nathandunn** [comment]
@hodgett  are you sure its memory related?    Can you show me the catalina.out and the javascript console?

**Comment by hodgett** [comment]
Where do I find these?

**Comment by hodgett** [comment]
> `Loaded Chado
Restarting tomcat with /var/lib/tomcat8
[FAIL] Starting Tomcat servlet engine: tomcat8 failed!
01-Mar-2019 21:09:27.539 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
01-Mar-2019 21:09:27.539 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
01-Mar-2019 21:09:27.539 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
01-Mar-2019 21:09:27.625 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
01-Mar-2019 21:09:27.652 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
01-Mar-2019 21:09:27.654 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 510 ms
01-Mar-2019 21:09:27.689 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
01-Mar-2019 21:09:27.689 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.14 (Debian)
01-Mar-2019 21:09:27.706 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
01-Mar-2019 21:09:27.726 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 71 ms
01-Mar-2019 21:09:37.732 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /var/lib/tomcat8/webapps/apollo.war
01-Mar-2019 21:09:47.507 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Configuring Shiro ...

Shiro Configured
2019-03-01 21:10:17,198 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table chadoprop add column cvterm_id int8 not null
2019-03-01 21:10:17,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "cvterm_id" contains null values
2019-03-01 21:10:17,211 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table chadoprop add constraint FK_8twb5n8vjmldyy3eeyq7sppc3 foreign key (cvterm_id) references cvterm
2019-03-01 21:10:17,211 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "cvterm_id" referenced in foreign key constraint does not exist
Starting Quartz Scheduler in QuartzFactoryBean
2019-03-01 21:10:28,170 [localhost-startStop-1] WARN  apollo.UserService  - User exists admin@local.host and can not be added again.
2019-03-01 21:10:29,237 [localhost-startStop-1] WARN  apollo.PhoneHomeService  - Failed to phone home: org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.bbop.apollo.ServerData] with identifier [150]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.ServerData#150]
2019-03-01 21:10:29,269 [Actor Thread 3] ERROR apollo.PhoneHomeService  - An error occured while phoning home Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.bbop.apollo.ServerData] with identifier [150]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.ServerData#150]
01-Mar-2019 21:10:29.429 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /var/lib/tomcat8/webapps/apollo.war has finished in 51,696 ms
2019-03-01 21:10:44,864 [http-nio-8080-exec-3] WARN  apollo.PreferenceService  - No user present, so using the client token
2019-03-01 21:10:44,941 [http-nio-8080-exec-4] ERROR apollo.PermissionService  - Username not supplied so can not authenticate.
2019-03-01 21:10:44,964 [http-nio-8080-exec-9] WARN  apollo.PermissionService  - Failed to authenticate user
2019-03-01 21:10:45,055 [http-nio-8080-exec-6] ERROR apollo.PermissionService  - Username not supplied so can not authenticate.
2019-03-01 21:11:05,786 [http-nio-8080-exec-6] WARN  apollo.PermissionService  - Failed to authenticate user
2019-03-01 21:11:05,787 [http-nio-8080-exec-6] WARN  apollo.SecurityFilters  - Authentication failed
2019-03-01 21:11:16,696 [http-nio-8080-exec-10] INFO  apollo.UserController  - updateTrackListPreference
2019-03-01 21:11:16,703 [http-nio-8080-exec-10] INFO  apollo.UserController  - Added userOrganismPreference false
2019-03-01 21:11:24,786 [http-nio-8080-exec-7] ERROR apollo.JbrowseController  - File not found: /data/NbAnnotFeb2019/tracks/Gmp_NbV1-genes/NbV1Ch13/trackData.json
01-Mar-2019 21:14:25.436 INFO [MessageBrokerSockJS-2] org.apache.coyote.AbstractProcessor.setErrorState An error occurred in processing while on a non-container thread. The connection will be closed immediately
 java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1262)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:670)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:607)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:597)
	at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:581)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:272)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1506)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:279)
	at org.apache.coyote.Response.action(Response.java:172)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:317)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:284)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:541)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
	at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:91)
	at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:345)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:325)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:249)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$1.run(AbstractSockJsSession.java:269)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by hodgett** [comment]
I don't know where to find catalina.out, the one on my host is zero length

**Comment by nathandunn** [comment]
@hodgett  In this case, what you are are seeing above is the `catalina.out`.

1. What are you seeing in the javascript console of your browser? 
1. What did your raw source data file look like? 
1. How did you process the tracks? 
1. If you turn off that track, does everything seem to work normally (a zoomed out screenshot would confirm this). 

Thanks.

**Comment by hodgett** [comment]
From the system info I see;
Max memory | 6257.246208 MB
Free memory | 145.815840 MB
Available processors | 2
Total memory | 636.080128 MB

I would like to increase the total memory like I have seen in other apollo installs, 636Mb is way too small. The BAM file is 250Gb. Only this track is showing the error, the other tracks display fine in the same window.  
`      {
         "baiUrlTemplate" : "raw/NbRNASeq_AllS.sorted.bam.bai",
         "key" : "NbRNASeq_AllS.sorted",
         "label" : "NbRNASeq_AllS.sorted",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "type" : "JBrowse/View/Track/Alignments2",
         "urlTemplate" : "raw/NbRNASeq_AllS.sorted.bam"
      }
`

**Comment by nathandunn** [comment]
That bam size won’t necessarily affect memory.  You need the chrome JavaScript console to see what the error is.

**Comment by hodgett** [comment]
`BlockBased.js:376 TypeError: Failed to fetch TypeError: Failed to fetch
_handleError @ BlockBased.js:376
inherited @ declare.js:214
_handleError @ CanvasFeatures.js:231
errorCallback @ CanvasFeatures.js:460
Promise.catch (async)
_getFeatures @ BAM.js:346
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getFeatures @ DeferredFeaturesMixin.js:31
fillFeatures @ CanvasFeatures.js:511
inherited @ declare.js:214
fillFeatures @ Alignments2.js:392
(anonymous) @ CanvasFeatures.js:208
(anonymous) @ lang.js:385
_getGlobalStats @ DeferredStatsMixin.js:36
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getGlobalStats @ DeferredStatsMixin.js:32
fillBlock @ CanvasFeatures.js:219
_showBlock @ BlockBased.js:484
(anonymous) @ BlockBased.js:244
showRange @ BlockBased.js:243
(anonymous) @ GenomeView.js:1820
(anonymous) @ GenomeView.js:1819
trackIterate @ GenomeView.js:2122
showVisibleBlocks @ GenomeView.js:1818
updateTrackList @ GenomeView.js:2219
showTracks @ GenomeView.js:1859
(anonymous) @ lang.js:383
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
(anonymous) @ Browser.js:1465
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
itemClick @ Hierarchical.js:186
(anonymous) @ Hierarchical.js:175
BlockBased.js:376 TypeError: Failed to fetch TypeError: Failed to fetch
_handleError @ BlockBased.js:376
inherited @ declare.js:214
_handleError @ CanvasFeatures.js:231
errorCallback @ CanvasFeatures.js:460
Promise.catch (async)
_getFeatures @ BAM.js:346
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getFeatures @ DeferredFeaturesMixin.js:31
fillFeatures @ CanvasFeatures.js:511
inherited @ declare.js:214
fillFeatures @ Alignments2.js:392
(anonymous) @ CanvasFeatures.js:208
(anonymous) @ lang.js:385
_getGlobalStats @ DeferredStatsMixin.js:36
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getGlobalStats @ DeferredStatsMixin.js:32
fillBlock @ CanvasFeatures.js:219
_showBlock @ BlockBased.js:484
(anonymous) @ BlockBased.js:244
showRange @ BlockBased.js:243
(anonymous) @ GenomeView.js:1820
(anonymous) @ GenomeView.js:1819
trackIterate @ GenomeView.js:2122
showVisibleBlocks @ GenomeView.js:1818
updateTrackList @ GenomeView.js:2219
showTracks @ GenomeView.js:1859
(anonymous) @ lang.js:383
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
(anonymous) @ Browser.js:1465
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
itemClick @ Hierarchical.js:186
(anonymous) @ Hierarchical.js:175
BlockBased.js:376 TypeError: Failed to fetch TypeError: Failed to fetch
_handleError @ BlockBased.js:376
inherited @ declare.js:214
_handleError @ CanvasFeatures.js:231
errorCallback @ CanvasFeatures.js:460
Promise.catch (async)
_getFeatures @ BAM.js:346
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getFeatures @ DeferredFeaturesMixin.js:31
fillFeatures @ CanvasFeatures.js:511
inherited @ declare.js:214
fillFeatures @ Alignments2.js:392
(anonymous) @ CanvasFeatures.js:208
(anonymous) @ lang.js:385
_getGlobalStats @ DeferredStatsMixin.js:36
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getGlobalStats @ DeferredStatsMixin.js:32
fillBlock @ CanvasFeatures.js:219
_showBlock @ BlockBased.js:484
(anonymous) @ BlockBased.js:244
showRange @ BlockBased.js:243
(anonymous) @ GenomeView.js:1820
(anonymous) @ GenomeView.js:1819
trackIterate @ GenomeView.js:2122
showVisibleBlocks @ GenomeView.js:1818
updateTrackList @ GenomeView.js:2219
showTracks @ GenomeView.js:1859
(anonymous) @ lang.js:383
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
(anonymous) @ Browser.js:1465
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
itemClick @ Hierarchical.js:186
(anonymous) @ Hierarchical.js:175
BlockBased.js:376 TypeError: Failed to fetch TypeError: Failed to fetch
_handleError @ BlockBased.js:376
inherited @ declare.js:214
_handleError @ CanvasFeatures.js:231
errorCallback @ CanvasFeatures.js:460
Promise.catch (async)
_getFeatures @ BAM.js:346
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getFeatures @ DeferredFeaturesMixin.js:31
fillFeatures @ CanvasFeatures.js:511
inherited @ declare.js:214
fillFeatures @ Alignments2.js:392
(anonymous) @ CanvasFeatures.js:208
(anonymous) @ lang.js:385
_getGlobalStats @ DeferredStatsMixin.js:36
(anonymous) @ lang.js:337
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
getGlobalStats @ DeferredStatsMixin.js:32
fillBlock @ CanvasFeatures.js:219
_showBlock @ BlockBased.js:484
(anonymous) @ BlockBased.js:244
showRange @ BlockBased.js:243
(anonymous) @ GenomeView.js:1820
(anonymous) @ GenomeView.js:1819
trackIterate @ GenomeView.js:2122
showVisibleBlocks @ GenomeView.js:1818
updateTrackList @ GenomeView.js:2219
showTracks @ GenomeView.js:1859
(anonymous) @ lang.js:383
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
(anonymous) @ Browser.js:1465
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
itemClick @ Hierarchical.js:186
(anonymous) @ Hierarchical.js:175
`

**Comment by hodgett** [comment]
`tenacious-fetch.m.js:2 GET https://sefapps06.qut.edu.au/apollo/31/jbrowse/data/raw/NbRNASeq_AllS.sorted.bam.bai net::ERR_CONTENT_LENGTH_MISMATCH 200
t @ tenacious-fetch.m.js:2
(anonymous) @ tenacious-fetch.m.js:2
t @ tenacious-fetch.m.js:2
(anonymous) @ tenacious-fetch.m.js:2
getfetch @ XHRBlob.js:30
_callee$ @ XHRBlob.js:209
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ XHRBlob.js:3
(anonymous) @ XHRBlob.js:3
(anonymous) @ XHRBlob.js:3
fetchBufferPromise @ XHRBlob.js:235
_callee2$ @ BlobFilehandleWrapper.js:65
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ BlobFilehandleWrapper.js:3
(anonymous) @ BlobFilehandleWrapper.js:3
(anonymous) @ BlobFilehandleWrapper.js:3
readFile @ BlobFilehandleWrapper.js:76
_callee2$ @ bai.js:121
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:36
(anonymous) @ asyncToGenerator.js:14
parse @ bai.js:201
_tinyMemoized @ bai.js:408
_callee4$ @ bai.js:343
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:36
(anonymous) @ asyncToGenerator.js:14
hasRefSeq @ bai.js:368
hasRefSeq @ bamFile.js:650
constructor @ BAM.js:233
(anonymous) @ declare.js:426
(anonymous) @ Browser.js:1622
(anonymous) @ lang.js:385
contextRequire @ main.bundle.js:313
req @ main.bundle.js:212
getStore @ Browser.js:1613
renderTrack @ GenomeView.js:2069
(anonymous) @ GenomeView.js:177
(anonymous) @ lang.js:385
_normalizedCreator @ Container.js:343
_normalizedCreator @ Selector.js:155
insertNodes @ Container.js:192
insertNodes @ Selector.js:172
showTracks @ GenomeView.js:1857
(anonymous) @ lang.js:383
dispatcher @ aspect.js:101
on.emit @ on.js:344
on.emit @ on.js:385
emit @ Evented.js:32
publish @ topic.js:25
publish @ Browser.js:1724
(anonymous) @ Browser.js:2380
(anonymous) @ lang.js:385
(anonymous) @ Browser.js:1818
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:902
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
(anonymous) @ Browser.js:890
(anonymous) @ lang.js:385
(anonymous) @ Browser.js:1818
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
afterMilestone @ Browser.js:1816
(anonymous) @ Browser.js:889
(anonymous) @ lang.js:385
(anonymous) @ Browser.js:1818
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:498
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:81
onLoad @ xhr.js:116
load (async)
addListeners @ xhr.js:144
xhr @ xhr.js:231
(anonymous) @ Browser.js:491
_milestoneFunction @ Browser.js:1792
loadRefSeqs @ Browser.js:448
(anonymous) @ Browser.js:88
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
(anonymous) @ Browser.js:85
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:246
notify @ Deferred.js:187
complete @ Deferred.js:168
resolve.callback @ Deferred.js:248
addResult @ DeferredList.js:54
(anonymous) @ DeferredList.js:37
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:277
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:542
finish @ lazyload.js:114
pollWebKit @ lazyload.js:329
setTimeout (async)
pollWebKit @ lazyload.js:338
setTimeout (async)
pollWebKit @ lazyload.js:338
load @ lazyload.js:250
finish @ lazyload.js:116
pollWebKit @ lazyload.js:329
setTimeout (async)
pollWebKit @ lazyload.js:338
load @ lazyload.js:250
css @ lazyload.js:367
_loadCSS @ Browser.js:541
(anonymous) @ Browser.js:269
forEach @ array.js:247
(anonymous) @ Browser.js:252
(anonymous) @ lang.js:385
contextRequire @ main.bundle.js:313
req @ main.bundle.js:212
(anonymous) @ Browser.js:249
_milestoneFunction @ Browser.js:1792
initPlugins @ Browser.js:191
(anonymous) @ Browser.js:83
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:1882
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:69
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:69
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:69
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
signalListener @ Deferred.js:45
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:81
onLoad @ xhr.js:116
load (async)
addListeners @ xhr.js:144
xhr @ xhr.js:231
load @ JB_json_v1.js:28
(anonymous) @ ConfigManager.js:144
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:141
(anonymous) @ ConfigManager.js:123
_loadRecur @ ConfigManager.js:121
(anonymous) @ ConfigManager.js:124
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:81
onLoad @ xhr.js:116
load (async)
addListeners @ xhr.js:144
xhr @ xhr.js:231
load @ JB_json_v1.js:28
(anonymous) @ ConfigManager.js:144
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:141
(anonymous) @ ConfigManager.js:123
_loadRecur @ ConfigManager.js:121
(anonymous) @ ConfigManager.js:124
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:81
onLoad @ xhr.js:116
load (async)
addListeners @ xhr.js:144
xhr @ xhr.js:231
load @ JB_json_v1.js:28
(anonymous) @ ConfigManager.js:144
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:141
(anonymous) @ ConfigManager.js:123
_loadRecur @ ConfigManager.js:121
_loadIncludes @ ConfigManager.js:135
(anonymous) @ ConfigManager.js:48
getFinalConfig @ ConfigManager.js:62
(anonymous) @ Browser.js:1860
_milestoneFunction @ Browser.js:1792
loadConfig @ Browser.js:1846
(anonymous) @ Browser.js:73
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
`

**Comment by nathandunn** [comment]
Looks like an error reading the index.

1. Does this happen for smaller BAM tracks? 
2. Does this happen for EVERY scaffold?
3. Does this happen for standalone JBrowse?

I would download and install the latest version of JBrowse:  http://jbrowse.org/ <http://jbrowse.org/>
And point it at that directory and see if you see the same error.   (You should be able to do an ./setup.sh && npm start)


If the answer to #3 is yes, I would post the issue (and the command you used to generate it) to the mailing list or as a JBrowse issue (once you confirm it):  http://jbrowse.org/contact.html <http://jbrowse.org/contact.html>

**Comment by nathandunn** [comment]
I'm going to close this for now.  Moving the original scope to #42

**Comment by nathandunn** [comment]
But feel free to re-open if still an issue.
