### ISSUE TITLE
[FAIL] Starting Tomcat servlet engine: tomcat8 failed!

### ISSUE THREAD

**Issue by chibante** [GMOD/docker-apollo#35]
Hi, guys!

I downloaded the Apollo (2.2.0 and latest) docker image and the container don't started. The tomcat fail: 
```
.
.
.
ALTER TABLE
ALTER TABLE
Loaded Chado
Restarting tomcat with /var/lib/tomcat8
**[FAIL] Starting Tomcat servlet engine: tomcat8 failed!**
08-Feb-2019 22:15:00.361 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
08-Feb-2019 22:15:00.361 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
08-Feb-2019 22:15:00.361 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
08-Feb-2019 22:15:00.467 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
08-Feb-2019 22:15:00.488 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
08-Feb-2019 22:15:00.490 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 580 ms
08-Feb-2019 22:15:00.535 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
08-Feb-2019 22:15:00.535 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.14 (Debian)
08-Feb-2019 22:15:00.548 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Feb-2019 22:15:00.599 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 108 ms
08-Feb-2019 22:15:10.587 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /var/lib/tomcat8/webapps/ROOT.war
08-Feb-2019 22:15:20.216 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Configuring Shiro ...

Shiro Configured
.
.
.
```
And the page not open:

![image](https://user-images.githubusercontent.com/46681974/52513464-0ce62480-2bf2-11e9-9ba0-54df2ce414a6.png)

In other image that I downloded last week it isn't happend. My server has a tomcat version 8.5.37 installed, is it a problem?  What could have happened?

Thanks! :)

**Comment by nathandunn** [comment]
It’s probably on port 8888 though I would have to see your docker command and the rest of the stack trace 

Nathan

**Comment by chibante** [comment]
Ups! :|

Sorry, I sent a wrong image...I tested both ports (8888, 8080) and the result was the same:

![image](https://user-images.githubusercontent.com/46681974/52537178-b17b7a00-2d4a-11e9-84dd-32e8c8f9aed3.png)

My docker command was:

`sudo docker run -it -p 8888:8080 -v /home/carla/Apollo/data:/data  quay.io/gmod/docker-apollo:latest`
```
.
.
```
![image](https://user-images.githubusercontent.com/46681974/52537234-73328a80-2d4b-11e9-8156-65ce11cac538.png)
```
.
.
```

Thanks! =)

**Comment by nathandunn** [comment]
Try logging into:

http:local:888/

The “apollo” shouldn’t be necessary.  Sorry for the confusion:





Nathan

**Comment by chibante** [comment]
Ok, no problem! :)

I tried `http:local:8888/` on **Google Chrome**:

![image](https://user-images.githubusercontent.com/46681974/52542340-d3462280-2d85-11e9-9bf8-8e1877025e52.png)

And **Firefox**:

![image](https://user-images.githubusercontent.com/46681974/52542359-038dc100-2d86-11e9-84e5-89e14256d5f2.png)

**Comment by nathandunn** [comment]
Sorry, I meant http://localhost:8888

**Comment by chibante** [comment]
I realized that there was an "8" less but I did't pay attention to the `local` instead of` localhost` 
Sorry!

It's ok now!
![image](https://user-images.githubusercontent.com/46681974/52542582-5c5e5900-2d88-11e9-9c62-886a108379f0.png)

But don't understend why the `tomcat` fail:
![image](https://user-images.githubusercontent.com/46681974/52542603-aa735c80-2d88-11e9-8ea7-44ac9f2aa312.png)

Do you know what's happen?

Thanks ;)

**Comment by nathandunn** [comment]
Not sure either.  Possibly it was already started.   But if you are seeing this page, then it must be working. 

Please close if you don't need anything further.

**Comment by chibante** [comment]
Thanks!!! =)
