### ISSUE TITLE
Tracks view give "Object Response" Error

### ISSUE THREAD

**Issue by csmibrahim** [GMOD/docker-apollo#41]
Hi, 
I have a working docker image from the GitHub but I get object Response error when I add tracks as shown below.
<img width="1440" alt="Screenshot 2019-05-28 at 20 22 52" src="https://user-images.githubusercontent.com/44603963/58551429-e6cbab00-8207-11e9-8d1e-8e88d6d55bf6.png">

The error in itself is not helpful to track the problems.

Other GitHub issue shows similar error and was fixed by adding permission in the httpd file. https://github.com/GMOD/jbrowse/issues/1242
But I am not sure where can I add this in Docker.

**Comment by csmibrahim** [comment]
Any idea?
Regards

**Comment by cmdcolin** [comment]
Looks like a 404 file not found for this URL. The JBrowse side of things did a couple updates to improve this error message, apologies for the vagueness. I don't know if there is something specific about docker apollo that causes this though

**Comment by nathandunn** [comment]
@csmibrahim  Some questions:

- Are you able to add a GFF3 file? 
- How are you mounting / running? 
- Where are the mounted files located?
- How are you adding the BAM files (manually or via upload)?
- Do you see any tomcat error logs (you have to be in the system to see them)?

**Comment by csmibrahim** [comment]
**Are you able to add a GFF3 file?**
-- No Many Perl packages missing and errors
**How are you mounting / running?**
-- I followed the step on the GitHub page. Running production using the build created by quay.io.
**Where are the mounted files located?**
-- All files at jbrowse-data folder as in the Example.
**How are you adding the BAM files (manually or via upload)?**
Manually.
**Do you see any tomcat error logs (you have to be in the system to see them)?**
Not sure where I can see them.

**Comment by nathandunn** [comment]
@csmibrahim  I am traveling this week, but I will try to test when I can.  I will need a bit more detail:

> Are you able to add a GFF3 file?
> -- No Many Perl packages missing and errors

Can you add a track by clicking on "New Track" here? 

![image](https://user-images.githubusercontent.com/751274/58587558-8e4ddb00-8212-11e9-9a48-324cc5305ad9.png)


> How are you mounting / running?
> -- I followed the step on the GitHub page. Running production using the build created by quay.io.

A specific command would be really helpful here, as I have lots of commands.   Feel free to obscure any local paths if need to, of course.

> Where are the mounted files located?
> -- All files at jbrowse-data folder as in the Example.

Could you provide a specific link to the example.  Sorry, we just have a ton of doc. 

> How are you adding the BAM files (manually or via upload)?
> Manually.

Can you post your `trackList.json` then.  Thanks.

> Do you see any tomcat error logs (you have to be in the system to see them)?
> Not sure where I can see them.

Let's not worry about that yet, but thanks for looking.

**Comment by csmibrahim** [comment]
**I followed the steps as in https://github.com/GMOD/docker-apollo read.me**

**Running with:** 
docker run -it -v /jbrowse/root/directory/:/data -v postgres-data:/var/lib/postgresql -p 8888:8080 quay.io/gmod/docker-apollo:latest

**Here the tracklist:**
{
   "tracks" : [
      {
         "key" : "Reference sequence",
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "category" : "Reference sequence",
         "label" : "DNA",
         "seqType" : "dna",
         "type" : "SequenceTrack",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
         "chunkSize" : 20000
      },
      {
         "label" : "CDB_bam",
         "key" : "CDB BAM",
         "urlTemplate" : "CDB.bam",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "type" : "JBrowse/View/Track/Alignments2"
      },
      {
         "type" : "JBrowse/View/Track/Alignments2",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "urlTemplate" : "PDB_sub.bam",
         "key" : "PDB BAM",
         "label" : "PDB_bam"
      }
   ],
   "formatVersion" : 1
}

**Comment by nathandunn** [comment]
So to clarify you have something like:
- `/jbrowse/root/directory/<organism name>`
- the organism it goes to is within apollo is `/data/<organism name`
- ls `/jbrowse/root/directory/<organism_name>` should yield (at a minimum):
   - trackList.json, PDB_sub.bam, PDB_sub.bam.bai, seq, tracks

**Comment by nathandunn** [comment]
It might work to upload the organism and GFF3 file:

![image](https://user-images.githubusercontent.com/751274/58634484-6796af80-82b9-11e9-94a4-92dd9bbf1a35.png)

**Comment by csmibrahim** [comment]
Yes, I have all of that and I uploaded the organism already from the interface successfully and all are fine.
Until I added tracks and try to see them on Jbrowser the error come.
For GFF3, when I run the flatfile-to-json i got endless missing Perl packages but this is not the issue her now.

**Comment by nathandunn** [comment]
Can you use the `new track` feature? 

https://github.com/GMOD/docker-apollo/issues/41#issuecomment-497090491

Also, I updated the quay image if you want to pull it `docker pull quay.io/gmod/docker-apollo:latest `

**Comment by csmibrahim** [comment]
Yes, this work perfectly. 

Previously I was following the data loading steps as in https://genomearchitect.readthedocs.io/en/latest/Data_loading.html.

Is there any new documents other than this I can follow?

**Comment by nathandunn** [comment]
@csmibrahim  There is not.  I will plan it for the 2.4.0 release.  

However, if you want to add any here to detail your process, https://github.com/GMOD/Apollo/blob/develop/docs/Data_loading.md  that would be awesome.

I can reformat / reorganize it later.

**Comment by nathandunn** [comment]
Can we close this, or are you still having trouble with BAM files using this mechanism?
