### ISSUE TITLE
GFF3 track not working

### ISSUE THREAD

**Issue by heshamgibriel** [GMOD/docker-apollo#47]
Hello,

I am trying to add a new repeat track using the GFF3 track (attached) and it got successfully loaded. However, I can't see the data as it only shows the loading sign without actual data!

Cheers,

![Screenshot from 2019-06-11 09-51-41](https://user-images.githubusercontent.com/39313063/59258094-2eeac480-8c2f-11e9-804d-a22c508104a0.png)

**Comment by nathandunn** [comment]
1 - what does the GFF3 look like (just a few samples)
2 - how did you add it (upload on the track panel, upload in the file menu, or by manually editing trackList.json)
3 - do you see any errors in the javascript console?

**Comment by heshamgibriel** [comment]
1- plz see gff 
![gff](https://user-images.githubusercontent.com/39313063/59288065-cd484b80-8c6a-11e9-97af-37c5c08ec03c.png)

2-I uploaded it by the upload on the track panel. I uploaded many gffs with this one, but this is the only gff that is not readable!!

3- yeah, I see this error(attached
![error](https://user-images.githubusercontent.com/39313063/59288261-4b0c5700-8c6b-11e9-96fa-ae29340adfea.png)
)

**Comment by nathandunn** [comment]
Perfect.  I'll take a look.

**Comment by cmdcolin** [comment]
The crash is due to the sequence-region line in your GFF not corresponding as expected

See the gff3 spec https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

```
##sequence-region seqid start end
The sequence segment referred to by this file, in the format "seqid start end". This element is optional, but strongly encouraged because it allows parsers to perform bounds checking on features. There may be multiple ##sequence-region directives, each corresponding to one of the reference sequences referred to in the body of the file, however only one ##sequence-region directive may be given for any given seqid. While a ##sequence-region pragma is not required for any or all landmark features when one is given all features on that landmark feature (having that seqid) must be contained within the range defined by that ##sequence-region diretive. An exception to this rule is allowed when a landmark feature is marked with the Is_circular attribute. In that case the features contained on that landmark may extend their coordiantes beyond the boundary as described above.
```

Also your column 9 is not formatted right I think too, it should use equals signs e.g. Target=...

**Comment by heshamgibriel** [comment]
I removed this line and formated col 9 as attached, but it's still not working!

![test3](https://user-images.githubusercontent.com/39313063/59291948-d7bb1300-8c73-11e9-8c9f-c68f1ee54862.png)

**Comment by cmdcolin** [comment]
@heshamgibriel Is there a new error?

**Comment by heshamgibriel** [comment]
yes (attached
![error_new](https://user-images.githubusercontent.com/39313063/59293230-aee84d00-8c76-11e9-9587-39554cfab035.png)
)

**Comment by nathandunn** [comment]
Is that the error you get when you click on and off repeats? 

In this case, I’m not seeing an error in the track or the console. 

Could you provide the revised GFF3 for repeats?  

Nathan

**Comment by heshamgibriel** [comment]
so this is the one that I used
![revised_repeats](https://user-images.githubusercontent.com/39313063/59293800-e3a8d400-8c77-11e9-830a-dc3fe115c15e.png)

**Comment by nathandunn** [comment]
Could you upload a text version of it? 

It might be an error in my upload code. 

Thanks,

Nathan

**Comment by heshamgibriel** [comment]
[test3.gff.txt](https://github.com/GMOD/docker-apollo/files/3277790/test3.gff.txt)

**Comment by nathandunn** [comment]
- [ ] install track with JBrowse
- [ ] attempt a manual configuration for the repeat masker
- [ ] emulate within the popup code for HTML Features, Canvas Features, and GFF3 and NCList types

**Comment by cmdcolin** [comment]
@nathandunn is it a jbrowse issue?

**Comment by nathandunn** [comment]
I don’t know.   

My hope is no and that it is an Apollo upload configuration issue.  

I need to test that.

**Comment by cmdcolin** [comment]
I can see from this that --type mRNA is added and the type in his gff is 'similarity' (e.g. they are not gene annotations)

```
grails-app/services/org/bbop/apollo/TrackService.groovy
744:        def arguments = [fileToExecute.absolutePath,"--gff",inputFile.absolutePath,"--compress","--type","mRNA","--trackLabel",outputName,"--out",trackPath]

```

**Comment by nathandunn** [comment]
Exactly.  I added it as a GFF3 with no topLevelFeature and it showed up.   However, it looked horrible.  

I'm going to see what types of inputs make the most sense.   Maybe just running the same command with `RepeatMasker` will be sufficient, and then I can update the UI to reflect that and limit these types of features to NCList only.    Conversely, it could simply automatically scan the file to check and query.

**Comment by cmdcolin** [comment]
I think you should consider just removing the --type mRNA if you are using jbrowse 1.16.4 or greater. JBrowse 1.16.4 introduced inferHTMLSubfeatures by @abretaud and this allows multiple transcripts to be created from a single gene parent feature

See release notes
https://github.com/GMOD/jbrowse/blob/master/release-notes.md#release-1164-----2019-04-10-165802-utc

1.16.5 will be released soon also and contains some more fixes related to using this with NeatFeatures I believe that @abretaud also made

**Comment by nathandunn** [comment]
@cmdcolin  / @abretraud this is awesome

For this, I think you are correct, just removing the --type works (and we are using whatever is on dev until 1.16.5 is  released). 

I'll add an option for non-transcript data that will accompany the upload.   Will try to get that out this week and update the docker image here.

**Comment by nathandunn** [comment]
will be fixed by https://github.com/GMOD/Apollo/issues/2181

**Comment by nathandunn** [comment]
Noted, I was able to get it working by dropping the `--type` command as @cmdcolin  suggested.  Now I just need to automate it:

![image](https://user-images.githubusercontent.com/751274/59370772-185c7000-8cf8-11e9-959f-053edb110cb0.png)

      ./bin/flatfile-to-json.pl --gff ./test_convert.gff3 --trackLabel RepeatTest --out /opt/apollo/human_test

**Comment by nathandunn** [comment]
@heshamgibriel  This should work now.    As soon as the docker finishes building I would do a docker pull and retry it:

https://quay.io/repository/gmod/docker-apollo?tab=builds
