### ISSUE TITLE
missing data folder

### ISSUE THREAD

**Issue by mictadlo** [GMOD/docker-apollo#5]
Hello, I cloned the `docker-apollo` project, but I can not do `Copy JBrowse folders into ./data`, because I do not know which `JBrowse folder` and `./data` is meant in QuickStart.

```
git clone https://github.com/GMOD/docker-apollo
ls docker-apollo/
Dockerfile      LICENSE         README.md       apollo-config.groovy    build.sh        docker-compose.yml  img
```

Thank you in advance.

Mic

**Comment by hexylena** [comment]
Hi @mictadlo 

If you wish to mount JBrowse instances within the docker image, there is no specific directory which you must use. You can mount any directory you like (e.g. `docker run -itP -v /my/data:/container/data gmod/apollo:latest`), and then in the Apollo interface you will specify the path to the JBrowse instances such as `/container/data/instance`

**Comment by mictadlo** [comment]
Does this docker container come with JBrowse or do I have to install it?

**Comment by hexylena** [comment]
The inputs to apollo is the data directory formatted for JBrowse. JBrowse is included as part of apollo, you just need to provide the "data" directory in your mounted volume

**Comment by nathandunn** [comment]
@mictadlo  I'm using the native docker for mac now (beta) and it all seems to be working when I use docker-compose.

**Comment by nathandunn** [comment]
The version is:  

```
$docker -v
Docker version 1.12.0, build 8eab29e, experimental
```

**Comment by mictadlo** [comment]
It is working.
