### ISSUE TITLE
database does not keep all files

### ISSUE THREAD

**Issue by mictadlo** [GMOD/docker-apollo#7]
Hi @erasche and @nathandunn ,
I uploaded yeast example to Apollo by using `create organism`. Next, I deleted the yeast folder from data folder and I got the following error:

```
Could not load the reference sequence definitions. RequestError: Unable to load data/refSeqs.json status: 404.
```

Is there a way to store all data inside the database in order to save space?

Thank you in advance,

Mic

**Comment by nathandunn** [comment]
So, the way it works we only store the scaffold data (reference sequences in `refSeqs.json`) for reference.   The track information is stored in the directory using regular JBrowse mechanisms and can be updated using trackList.json.  Some of the data can be loaded via [REST](http://gmod.org/wiki/JBrowse_Configuration_Guide#Writing_JBrowse-compatible_Web_Services), as well (and so not stored in the directory) and configured in the trackList.json

You should be able to configure additional room or use a symlink.
