### ISSUE TITLE
docker-compose down removes Organism

### ISSUE THREAD

**Issue by mictadlo** [GMOD/docker-apollo#8]
Hi @erasche and @nathandunn,
How is it possible to avoid that `docker-compose down` deletes Organism?

Thank you in advance,

Mic

**Comment by hexylena** [comment]
Hi @mictadlo it does not, in my experience (but I only run GNU/linux)

If you are using an explicit volume for the postgres database, then the data will be persisted in that directory.

If you are not using an explicit volume, then the volume should be persisted in the docker directory and used automatically.

I would guess that this is another OSX oddity.

**Comment by mictadlo** [comment]
I am running OS X as host and Linux Mint is installed in VirtualBox. How would I need to change the `docker-compose.yml` to explicitly be able to use volume for postgres database in order persist the data?

**Comment by hexylena** [comment]
https://github.com/GMOD/docker-apollo/blob/master/docker-compose.yml#L35 should be sufficient.

Are you running docker inside the Linux Mint guest VM?

**Comment by mictadlo** [comment]
Yes, I am running docker inside Linux Mint 18 VM. 
1.  What kind of difference would this make `/srv/docker/postgresql:/var/lib/postgresql` as describe [here](https://github.com/sameersbn/docker-postgresql/blob/master/docker-compose.yml)?
2. What happens if e.g postgres image get security updates.  How can I update the image without losing data stored in the database?

**Comment by mictadlo** [comment]
...
I watched this [video](https://www.youtube.com/watch?v=rlK1JYsM6Aw) and the solution was `docker run --rm --volumes-from john1 -v $(pwd):/backup busybox tar cvf /backup/john2.tar /john`. Probably to backup the database it would be necessary to dump it somehow.

**Comment by hexylena** [comment]
1. No difference, that is the same. Just mounts a different directory.
2. The postgres database is stored as files on disk. If the image gets (security, or other) updates that required changes to the on-disk format, postgres would handle that.

As for backing up the database, it is much simpler to do something like:

``` console
$ docker exec -it my-postgres-image-id pg_dump -U postgres | gzip > my-backup.sql.gz
```

to dump the database. If you are even braver, you could just backup your mounted volume directory, which should work in theory, but I would only do that with the image turned off (just like backing up a regular postgres instance, wouldn't want to copy possibly mid-write, and corrupted files)
